sudo: required #hey travis we need superuser level permissions 
language: generic

services:
  - docker #travis ci install docker in our container 

before_install:
  - docker build -f Dockerfile.dev -t koustavs18/docker-react . 

script:
  - docker run -e CI=true koustavs18/docker-react npm run test

#Deployment application in elasticbeanstalk 

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-225096658367"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY


