sudo: required #hey travis we need superuser level permissions 
language: generic

services:
  - docker #travis ci install docker in our container 

before_install:
  - docker build -f Dockerfile.dev -t koustavs18/docker-react . 

script:
  - docker run -e CI=true koustavs18/docker-react npm run test